language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - npm install --save-dev
  - bower install
  - grunt version:patch
  - git add .
  - grunt buildcontrol:version
script:
  - grunt
after_success:
  - grunt deploy
after_failure:
after_script:
services: mongodb

